#!/usr/bin/env python
# coding: utf-8

"""CAN-MIRGU Dataset loader — Pi6 (real, moving-vehicle CAN attacks, 2024).

The dataset's official UCI Machine Learning Repository file
(https://archive.ics.uci.edu/static/public/1035/can-mirgu.zip, the
"Download" button's real target) is confirmed corrupted as hosted -- two
independent HTTP clients (curl and PowerShell's Invoke-WebRequest)
downloaded byte-identical, unparseable zip data from it (no valid local
file header anywhere in the file). This loader still tries that URL first
in case UCI fixes it, but the real working source turned out to be the
dataset author's own Google Drive folder linked from
https://github.com/sampathrajapaksha/CAN-MIRGU's readme -- that folder *is*
the full dataset (not the small "Sample dataset" also in that repo), just
split by Google's own folder-download zipping into
``CAN-MIRGU-<timestamp>-1-00{1,2,3}.zip``. Since Drive folder downloads
aren't reliably scriptable (the zip is generated by an internal web-app
call, not a stable URL), auto-download here targets three direct Drive
file links instead: each of those three parts uploaded to this project's
own Drive, downloaded the same way as CICIoV2024's Google Drive mirror in
``Pi4/ciciov_utils_cav.py`` (including handling Google's large-file
virus-scan interstitial page, which is much more likely to trigger here
given these files are 300-400MB each). If every automatic path fails,
download manually via either URL above and place the extracted files
anywhere under ``CAN-MIRGU/`` next to this file.

Structure and format (confirmed against the real, full downloaded
dataset -- 48 candump ``.log`` files, ~5.5GB uncompressed): a top-level
``Benign/`` folder with ``Day_1`` .. ``Day_6`` subfolders, and an
``Attack/`` folder containing ``Real_attacks/``, ``Masquerade_attacks/``,
and ``Suspension_attacks/`` subfolders. Every file is a standard
``(timestamp) can0 ID#HEXDATA ...`` candump capture, parsed the same way
as ROAD. Files are classified Normal/Attack by path (containing
"normal"/"ambient"/"benign" -> Normal; containing "attack" -> Attack),
which matches this real layout without requiring the folders to be
renamed. CSV support is kept as a fallback in case a manually-placed copy
uses that format instead, resolved the same flexible way as CICIoV2024.

Labeling caveat: whole-file labeling is used because each attack capture is
its own dedicated file per attack scenario (e.g.
``Break_warning_attack.log``, ``Min_speedometer_attack_1.log``), separate
from the ``Benign/Day_*`` normal-driving captures -- confirmed by file
listing, not by inspecting row-level ground truth. Unlike ROAD, CAN-MIRGU
ships no interval/metadata file alongside the logs, so there's no
finer-grained timing information to use even if a capture did interleave
normal and injected traffic. TODO: if per-row ground truth is ever
published for this dataset, switch to interval-based labeling like
``road_utils_cav.py``.
"""

import glob
import os
import urllib.request
import zipfile

import numpy as np
import pandas as pd

import common_cav

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
CANMIRGU_DIR = os.path.join(BASE_DIR, "CAN-MIRGU")
DATASET_KEY = "canmirgu"
UCI_ZIP_URL = "https://archive.ics.uci.edu/static/public/1035/can-mirgu.zip"
SOURCE_URLS = (
    "https://archive.ics.uci.edu/dataset/1035/can-mirgu",
    "https://github.com/sampathrajapaksha/CAN-MIRGU",
)
# The GitHub readme's Google Drive folder, split into 3 parts by Google's
# own folder-download zipping, each re-uploaded to this project's own
# Drive (see module docstring) so it can be downloaded by direct file ID.
GOOGLE_DRIVE_FILE_IDS = (
    "1QZZLbA5fkjc_DdBfSvDYk1Zm03ysZA2V",  # CAN-MIRGU-...-1-001.zip
    "1EkPUOtpBUtyZpP811QS_bA3htbFPHuff",  # CAN-MIRGU-...-1-002.zip
    "1xgyNExQi02eY38UOCzkH040INVshCw6u",  # CAN-MIRGU-...-1-003.zip
)

CANDIDATE_ID_COLUMNS = ["ID", "id", "can_id", "CAN_ID", "CAN ID", "Arbitration_ID"]
CANDIDATE_DLC_COLUMNS = ["DLC", "dlc"]
CANDIDATE_DATA_COLUMNS = [
    [f"DATA{i}" for i in range(8)],
    [f"DATA_{i}" for i in range(8)],
    [f"Data{i}" for i in range(8)],
    [f"data{i}" for i in range(8)],
]
NORMAL_TOKENS = ("normal", "ambient", "benign")
ATTACK_TOKENS = ("attack",)

# CAN-MIRGU's raw .log captures total ~127M CAN frames -- loading every row
# exhausted 16GB of RAM before this was added (see module docstring). Keep
# 1-in-20 frames (~5%, matching this project's existing Car-Hacking
# down-sampling convention), which brings the row count down to a size
# comparable to the other 5 datasets (a few million rows) while still
# sampling frames spread across each capture's full duration.
LOG_SAMPLE_STRIDE = 20

reshape_for_cnn = common_cav.reshape_for_cnn


def _find_files():
    csv_files = glob.glob(os.path.join(CANMIRGU_DIR, "**", "*.csv"), recursive=True)
    log_files = glob.glob(os.path.join(CANMIRGU_DIR, "**", "*.log"), recursive=True)
    return sorted(csv_files + log_files)


def _extract_all_nested_zips() -> None:
    """UCI's archive is a zip inside a zip, and a few individual captures
    are further zipped on their own; keep extracting until none remain.
    """
    while True:
        nested = glob.glob(os.path.join(CANMIRGU_DIR, "**", "*.zip"), recursive=True)
        if not nested:
            return
        for zip_path in nested:
            with zipfile.ZipFile(zip_path, "r") as zf:
                zf.extractall(os.path.dirname(zip_path))
            os.remove(zip_path)


def _download_canmirgu_from_uci() -> None:
    os.makedirs(CANMIRGU_DIR, exist_ok=True)
    zip_path = os.path.join(CANMIRGU_DIR, "canmirgu_download.zip")
    urllib.request.urlretrieve(UCI_ZIP_URL, zip_path)
    with zipfile.ZipFile(zip_path, "r") as zf:
        zf.extractall(CANMIRGU_DIR)
    os.remove(zip_path)
    _extract_all_nested_zips()


def _download_canmirgu_from_drive_mirror() -> None:
    os.makedirs(CANMIRGU_DIR, exist_ok=True)
    for i, file_id in enumerate(GOOGLE_DRIVE_FILE_IDS, start=1):
        zip_path = os.path.join(CANMIRGU_DIR, f"canmirgu_part_{i}.zip")
        common_cav.download_from_google_drive(file_id, zip_path)
        with zipfile.ZipFile(zip_path, "r") as zf:
            zf.extractall(CANMIRGU_DIR)
        os.remove(zip_path)


def _ensure_raw_files() -> list:
    files = _find_files()
    if files:
        return files

    errors = []
    for source_name, download_fn in (
        ("UCI", _download_canmirgu_from_uci),
        ("Google Drive mirror", _download_canmirgu_from_drive_mirror),
    ):
        try:
            download_fn()
        except Exception as error:
            errors.append(f"{source_name}: {error}")
            continue
        files = _find_files()
        if files:
            return files

    raise FileNotFoundError(
        f"No CAN-MIRGU capture files found under '{CANMIRGU_DIR}', and "
        f"every automatic download attempt failed ({'; '.join(errors)}). "
        f"Download manually from {' or '.join(SOURCE_URLS)} and place the "
        f"extracted files under '{CANMIRGU_DIR}'."
    )


def _classify_label(path: str) -> str:
    lower_path = path.lower()
    if any(token in lower_path for token in NORMAL_TOKENS):
        return "Normal"
    if any(token in lower_path for token in ATTACK_TOKENS):
        return "ATTACK"
    raise ValueError(
        f"Could not classify '{path}' as Normal or Attack from its path. "
        f"Expected 'normal'/'ambient'/'benign' or 'attack' to appear in the "
        f"filename/folder name."
    )


def _resolve_data_columns(df: pd.DataFrame):
    for candidate_set in CANDIDATE_DATA_COLUMNS:
        if all(name in df.columns for name in candidate_set):
            return candidate_set
    raise ValueError(
        f"Could not find 8 DATA columns (tried {CANDIDATE_DATA_COLUMNS}) in "
        f"CAN-MIRGU CSV columns: {list(df.columns)}"
    )


def _rows_from_csv(path: str):
    df = pd.read_csv(path)
    id_col = next((c for c in CANDIDATE_ID_COLUMNS if c in df.columns), None)
    dlc_col = next((c for c in CANDIDATE_DLC_COLUMNS if c in df.columns), None)
    if id_col is None:
        raise ValueError(f"Could not find a CAN ID column in {path}: {list(df.columns)}")
    data_cols = _resolve_data_columns(df)

    rows = []
    for _, row in df.iterrows():
        can_id = int(row[id_col]) if not isinstance(row[id_col], str) else int(str(row[id_col]), 0)
        dlc = int(row[dlc_col]) if dlc_col is not None else 8
        data_bytes = [int(row[c]) for c in data_cols]
        rows.append((None, can_id, dlc, data_bytes))
    return rows


def _rows_from_file(path: str):
    if path.lower().endswith(".csv"):
        return _rows_from_csv(path)
    return common_cav.iter_candump_file(path, stride=LOG_SAMPLE_STRIDE)


def _load_raw_canmirgu():
    files = _ensure_raw_files()

    # GrowableArray fills numpy buffers directly instead of accumulating
    # Python lists first -- with ~6M sampled rows expected, a plain list-of-
    # lists approach here is what previously exhausted 16GB of RAM.
    features = common_cav.GrowableArray(num_cols=10, dtype=np.float32)
    labels = common_cav.GrowableArray(num_cols=1, dtype=np.int64)

    for path in files:
        label_value = common_cav.LABEL_TO_INT[_classify_label(path)]
        for _, can_id, dlc, data_bytes in _rows_from_file(path):
            features.append(common_cav.build_frame_features(can_id, dlc, data_bytes))
            labels.append((label_value,))

    return features.finalize(), labels.finalize().ravel()


def get_global_train_test_split(test_size: float = 0.33, random_state: int = 41):
    files = _ensure_raw_files()
    source_version = common_cav.directory_signature(files)
    return common_cav.cache_scaled_split(
        DATASET_KEY, _load_raw_canmirgu, source_version, BASE_DIR,
        test_size=test_size, random_state=random_state,
    )


def get_client_data(test_size: float = 0.33, random_state: int = 41, local_val_size: float = 0.2):
    x_train_pool, _, y_train_pool, _ = get_global_train_test_split(test_size, random_state)
    return common_cav.local_train_val_split(x_train_pool, y_train_pool, local_val_size, random_state)


def get_test_split(test_size: float = 0.33, random_state: int = 41):
    _, x_test, _, y_test = get_global_train_test_split(test_size, random_state)
    return x_test, y_test
